# SecureChests
# You can now use the following settings to configure
# SecureChests to lock Chests, Furnaces, Dispensers & Doors.
# 
Chest: true
Furnace: true
Dispenser: true
TrapDoor: false
Door: false